apiVersion: v1
kind: Service
metadata:
  name: php-frontend
  labels:
    app: php-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
  selector:
    app: php-frontend


