apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-frontend
  labels:
    app: php-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: php-frontend
  template:
    metadata:
      labels:
        app: php-frontend
    spec:
      containers:
        - name: php-frontend
          image: "{{ .Values.frontend.image }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: DB_HOST
              value: {{ .Values.frontend.env.DB_HOST }}
            - name: DB_USER
              value: {{ .Values.frontend.env.DB_USER }}
            - name: DB_PASSWORD
              value: {{ .Values.frontend.env.DB_PASSWORD }}
            - name: DB_NAME
              value: {{ .Values.frontend.env.DB_NAME }}

